### ISSUE TITLE
association rules code

### ISSUE THREAD

**Issue by candymin** [spencebeecher/Association-Rule-Learning-With-Hadoop#1]
hello,I download your code to implement ft-tree ,and  frequent items are already generated.But I don't know how  to write the code about generate association rules

**Comment by spencebeecher** [comment]
Hello! Thanks for asking your question. There are two scripts - the first generates itemsets and the second generates rules from itemsets. Have you tried the second script?

**Comment by spencebeecher** [comment]
It has been a few days - I am going to close this but please open another issue if you still have questions.
